### PR TITLE
Added workspace load and save to file ability.

### PR DESCRIPTION
**Pull request by AndriyPt**
Tested on latest Chrome and Firefox on Ubuntu 14.04 and IE 10 on Windows 8.

### CODE REVIEW

**Comment by AndriyPt** [comment]
This is how it looks on the web page
image

**Comment by ugocupcic** [comment]
Any news on merging this? Let us know if there's anything we can do to help speed up the merge.

**Comment by imuguruza** [comment]
Hi @ugocupcic, we'll check this in short

**Comment by ugocupcic** [comment]
@imuguruza OK great thanks. We've started using your (awesome) robot-blockly interface for our bots and are going to being sharing a few generic pull requests like this one.

**Comment by imuguruza** [comment]
Great @ugocupcic !

**Comment by Nestor94Gonzalez** [comment]
Thanks for the contribution @AndriyPt @ugocupcic !
Tested and it works properly, this should be merged soon.

**Comment by ugocupcic** [comment]
OK great thanks for the review. #19 is quite exciting as well ;)

**Comment by vmayoral** [comment]
Thanks @AndriyPt, merged.

**Pull request merged**
